// RESPOSTA:
// Colocarei o local do cruzamento sendo Riberão preto tendo a equação horária do carro como 
// S1 = 110*t
// E a do caminhão que sai de um local a 100km de distancia do local de cruzamento :
// S2 = 100 - 80*t 
// temos que o tempo do caminhão irá ser igual a 1,25 horas porém temos que como ele perder 10 minutos nos pedagios que é equivalente a 0,17horas temos que na verdade será igual a 1,42 horas podendo assim calcular realmente sua velocidade media durante o perurso que será 
// 100 km / 1,42 = 70,6 km/h
// tendo assim  S2 = 100 - 70,6*t
//podemos igualar S2 = S1 por estarem se cruzando no mesmo ponto
// 110*t = 100 - 70,6t
//temos :
// 100 = 180,6t
//t = 0,553709856
//temos que na equação 01:
// S1 = 60,9
//na equação 02;
//S2 = 60,9
//Então temos que os dois veiculos estão a mesma distancia de ribeirão preto
